# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 30
# Label requiring a response
responseRequiredLabel: question
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  This issue has been automatically closed for inactivity. Feel free to re-open it
  if you you have any new information or follow up questions regarding the original
  topic of the issue.
  If you have some other questions or issue, please open a new issue.
